name: Release
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
          architecture: 'x64'

      - name: install platform dependencies
        working-directory: ./zedd-platform
        run: npm install
      - name: build platform
        working-directory: ./zedd-platform
        run: npm run build

      - name: install app dependencies
        working-directory: ./zedd-app
        run: npm install

      - name: build release
        working-directory: ./zedd-app
        run: npm run make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: generate and upload latest.yml (Windows only)
        if: runner.os == 'Windows'
        working-directory: ./zedd-app
        run: node scripts/generate-latest-yml.js --publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          draft: true
          files: |
            ./zedd-app/out/**/*.snap
            ./zedd-app/out/**/*.dmg
            ./zedd-app/out/**/*.zip
            ./zedd-app/out/make/squirrel.windows/x64/*Setup.exe
            ./zedd-app/out/make/squirrel.windows/x64/latest.yml
            ./zedd-app/out/make/squirrel.windows/x64/RELEASES
            ./zedd-app/out/make/squirrel.windows/x64/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}